version: "3.3"
services:
  service.naiveproxy:
    image: 1andonli/naiveproxy:latest
    container_name: naiveproxy
    network_mode: host
    restart: unless-stopped
    volumes:
      - './config.json:/app/config.json'
