name: build

on:
  push:
    branches: [master]
    paths-ignore: [README.md]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          include:
            - platform: linux/amd64
              arch: linux-x64
            - platform: linux/arm64
              arch: linux-arm64
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 1andonli/naiveproxy
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ matrix.platform }}
          build-args: ARCH=${{ matrix.arch }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
